### PR TITLE
Add Drone, Graphene, JUnit, Persistence

### PR DESCRIPTION
**Pull request by aslakknutsen**
Current setup allows us to use the target user view, but it has two issues:

To avoid having to define <type>pom</type> in the user view each 'rename artifact' is packaging jar and creates a empty jar that has really no purpose
Being of type jar, Maven complain if we try to use it with <scope>import</scope> in depmgm. This results in a lot of duplicate definitions within the dependency hierarchy, e.g. Graphene repeats the Drone section instead of simply import the universe:drone artifact.

It feels more correct to have the universe rename artifacts as type pom, but that will result in a user view  like this:

```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.arquillian</groupId>
                <artifactId>arquillian-universe</artifactId>
                <version>1.0.0.Alpha1-SNAPSHOT</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>
    
    <dependencies>
        <dependency>
            <groupId>org.arquillian.universe</groupId>
            <artifactId>arquillian-junit</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>org.arquillian.universe</groupId>
            <artifactId>arquillian-graphene</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>org.arquillian.universe</groupId>
            <artifactId>arquillian-persistence</artifactId>
            <type>pom</type>
        </dependency>
        
    </dependencies>
```

note: Added universe-test module just to be able to study the resolved dependencies when used by a user.

note: Direct dependencies of a imported pom are not resolved as part of the tree. e.g. arquillian-universe can't add direct dependency to e.g. shrinkwrap-resolver. This dependency is never reflected in the users dependency tree unless you depend on the universe-pom as well as import it.

Additions for https://github.com/arquillian/arquillian-universe-bom/issues/1

### CODE REVIEW

**Comment by lordofthejars** [comment]
Well I don't see anything wrong on using the `<type>pom</type>`

**Comment by aslakknutsen** [comment]
Just extra stuff to add, but I guess we can live with that.. :)

**Comment by aslakknutsen** [comment]
I'll redo and send a new pr

**Comment by aslakknutsen** [comment]
pr updated.. :)

**Pull request merged**
